spring:
  application:
    name: EmployeeDirectory

  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: Mystiquex@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        envers:
          audit_table_suffix: "_AUD" # Default, can be customized
          default_schema: "employee" # Optional
          revision_field_name: "revision_id" # Matches your CustomAuditEntity
          revision_type_field_name: "revision_type"
          global_with_modified_flag: true # Track changed fields
          store_data_at_delete: true # Sto

  sql:
    init:
      # Set to 'never' to avoid conflicts with Flyway.
      mode: always

  jackson:
    time-zone: UTC

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: employee,audit_schema
    default-schema: employee
    table: flyway_schema_history

server:
  port: 8080
  servlet:
    context-path: /ems

randomuser:
  enabled: true
  base-url: https://randomuser.me/api/